version: "3.7"

services:

  front: 
    container_name: front
    build: ./front
    volumes:
    - front:/front-app/
    ports:
      - 9000:80
    depends_on:
      - mongo

  back: 
      container_name: back
      image: node
      build: ./back
      command: bash -c "npm start"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data:/data/db/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 28017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: azerty
      ME_CONFIG_MONGODB_URL: mongodb://root:michel:27017/

volumes:
  front:
  data:
